services:
  kinect-base:
    build:
      context: ./libs
      dockerfile: Dockerfile
    image: kinect-base

  app:
    container_name: kinect-app
    build:
      context: ./app
      dockerfile: Dockerfile
    image: kinect-app-rest
    devices:
      - /dev/bus/usb:/dev/bus/usb
    privileged: true
    user: root
    depends_on:
      - kinect-base

  mongo:
    image: mongo:7.0
    container_name: sensor-data-mongo-db
    command: ["mongod", "--logpath", "/var/log/mongodb/mongod.log", "--logappend"] 
    env_file:
        - .env
    volumes:
        - mongo_data:/data/db
        - mongo_logs:/var/log/mongodb

volumes:
  mongo_data:
  mongo_logs:
